### ISSUE TITLE
Bug connecting to Facebook account

### ISSUE THREAD

**Issue by avewrigley** [idno/Facebook#12]
Installed Facebook plugin on my idno server, and getting the following bug:
1. click on "Settings" -> "Facebook"
2. click on "Click here to connect Facebook to your account"

page refreshes .... nothing happens. Rinse and repeat.

Ave.

**Comment by andru** [comment]
I'm also getting this problem. 

No errors in the console. The button anchor doesn't have a `href`attribute and the only click handler attached to it is:

`    $('body').on('click', function (event, el) {
        var clickTarget = event.target;

        if (clickTarget.href && clickTarget.href.indexOf(window.location.origin) === -1) {
            clickTarget.target = "_blank";
        }
    });`

from `embed.js`.

Anyone have a clue?
