### ISSUE TITLE
[UX] Add a label indicating the account type

### ISSUE THREAD

**Issue by Phyks** [idno/Facebook#19]
Hi,

When adding multiple accounts for Facebook, Twitter and so on, we often have the same username on multiple of them.

Then, it is difficult to correctly know which input button corresponds to which account.

Thanks

**Comment by benwerd** [comment]
This should be fixed in the very latest code: we've added service icons.

**Comment by Phyks** [comment]
This is only for Facebook of for any service? I do not see them with Twitter as well (and do not have Facebook on my Known, just saw it on a friend's instance).

**Comment by schiesbn** [comment]
I also can't see them and I just did a git pull so I should have the latest code.

The Facebook button just shows "Facebook", the Twitter button my twitter name and the LinkedIn Button my LinkedIn name but no indicator which button belong to which network (beside the generic string "Facebook" for the facebook button)

**Comment by benwerd** [comment]
Does this still occur if you disconnect and reconnect your accounts?

**Comment by erinjo** [comment]
@schiesbn You should see each of the toggles with the social network icon and your username for the account.  We have icons in place for every social network that Known supports. We also use a fallback share icon for connections like webhooks.
Occasionally ad blockers remove the icons for the various social networks.  We've worked hard to try to prevent this, but it still might be a possibility depending on the ad blocker.  Do you have any ad blockers installed in your browser?
![screen shot 2015-03-16 at 4 23 13 pm](https://cloud.githubusercontent.com/assets/1192220/6678579/79e67592-cbf9-11e4-95b0-d8df4ac41f6c.png)

**Comment by benwerd** [comment]
In addition to @erinjo's explanation, it's worth saying that very legacy connections (ones that were originally made in October or earlier) will not contain the name of the account. This is because we originally only allowed you to authenticate with a single account per social media service. All new connections should store and display the account name.

**Comment by schiesbn** [comment]
I removed the Facebook connection and re-created it. Now all buttons are consistent and show my account name. But the icons are still not visible. I have Adblock Plus installed, but disabling it also doesn't help. Any other idea? My web server is only available over https don't think that this is a problem but want to mention it anyway.

**Comment by schiesbn** [comment]
After moving my instance from git master to your latest release (tar file) the icons are shown. Don't know what was wrong with my git installation. Anyway, thanks for your help!
