### ISSUE TITLE
 (#200) The user hasn't authorized the application to perform this action 

### ISSUE THREAD

**Issue by cphyc** [idno/Facebook#20]
I installed idno on two distincts server and I was able to make the Facebook plugin work for only one of them, the other one getting the error : " (#200) The user hasn't authorized the application to perform this action ". When I try to grant my application the rights on my Facebook account, I get the message saying 

```
Submit for Login Review
Some of the permissions below have not been approved for use by Facebook.
Submit for review now or learn more.
```

and the mention

```
This does not let the app post to Facebook. 
```

**Comment by benwerd** [comment]
It's worth making sure that you have set the correct domain in Facebook's developer panel, and enabled the app (i.e., don't just set it in debug mode). You don't need to get their permission to post if you're the only user; you _will_ need to get Facebook's approval if you want more people to use your Known site.

We may set something up to let you use withknown.com's syndication service in the future, so you don't need to mess with Facebook's API at all if you don't want to.

**Comment by cphyc** [comment]
That's where I have an issue, the app is public and available to all users and the domain is the right one, but I still can't get the write permission, even though the app has been created by the account that tries to access it.

**Comment by benwerd** [comment]
That's weird. And the app is linked to that same Facebook account as the administrator?

**Comment by cphyc** [comment]
It is yes.

**Comment by mapkyca** [comment]
Old ticket, can't replicate, closing.
