### ISSUE TITLE
Is removing links the right thing to do?

### ISSUE THREAD

**Issue by jarofgreen** [idno/Facebook#24]
I posted this https://jarofgreen.co.uk/2015/20-days-to-election-added-meetyournextmp-750-hustings-in-230

>   http://democraticdashboard.com/ added @MeetYourNextMP

The FB post removed links so it looked like 

> added @MeetYourNextMP

which doesn't really make any sense any more.

Is removing links from the text the right thing to do?

**Comment by mapkyca** [comment]
AFAIK this is facebook stripping (some but not all) links.
