### ISSUE TITLE
Is the app really need to be submitted for review?

### ISSUE THREAD

**Issue by MatthieuScarset** [idno/Facebook#26]
Hi, 

I've created a Facebook App 
Then, get my App ID and Password
Then, login to Facebook and select only my Facebook Page to be connected

Now, I share content on my Known website and I'd like it to be shared on my Facebook Page...

Unfortunately, nothing is published on Big Brother plateform.

I've tried to deauthorize and reconnect to my app and it says "This app need to be submit for review before being able to Publish".

How can I make your Plugin to work ?

**Comment by benwerd** [comment]
You shouldn't need to submit the Facbeook plugin for review if you're using it as a single user (unless Facebook have changed an aspect of their platform, which is possible). As soon as you add a second user, you will need to submit it for review.

**Comment by MatthieuScarset** [comment]
Hi

As discussed on Twitter,I got my app submitted with manage pages and publish pages permission 

However, my posts are not published to Fb

**Comment by mapkyca** [comment]
You need to activate it, i.e. take it out of dev mode, for your posts to be seen by anyone other than you. IIRC there is a "submit for review", but this is automated and done in a few minutes.
