### ISSUE TITLE
Facebook Connect Error

### ISSUE THREAD

**Issue by finalcut** [idno/Facebook#27]
I receive the following error when trying to connect Known to Facebook via the Account Settings - Facebook option.  

```
Invalid Scopes: publish_stream, offline_access. This message is only shown to developers. 
Users of your app will ignore these permissions if present. Please read the documentation for valid
 permissions at: https://developers.facebook.com/docs/facebook-login/permissions
```

NOTE: I have already created the app, added an email address, and marked it public via Site Configuration - Facebook.

I deleted the first app and tried again to be on the safe side but receive the same error message.

**Comment by mapkyca** [comment]
Old/worksforme
