### ISSUE TITLE
remove See Original link

### ISSUE THREAD

**Issue by kylewm** [idno/Facebook#31]
The "See Original" link has been on a downward streak for a while. It is now invisible in Facebook posts (only available through the API), causes problems [sharing links to Youtube](https://groups.google.com/forum/?fromgroups#!searchin/known-dev/see$20original/known-dev/GEAjieyQdck/dcK-rrjYBgAJ), [rewrites the year in permalinks](https://github.com/snarfed/bridgy/issues/611), and [just generally seems unsupported and unstable](http://indiewebcamp.com/POSSE_to_Facebook#Warning_against_using_See_Original).

Unfortunately there is not a good substitute. Including the `(Original: http://...)` link in the post body is pretty ugly. And Bridgy can't do POSSE post discovery on Facebook very well at all because Facebook.

cc: @tinokremer

**Comment by physcocode** [comment]
As i constantly suggest the Facebook platform policy itself restrict see original , so its time to put that into grave a best fix solution !

**Comment by matzoman** [comment]
right now, when you syndicate a photo to facebook, a "Original: [url]" link is included on FB and brid.gy can collect "likes" and "comments" from fb back to my site.

Example:
Blog: http://known.matthias.welling.io/2016/letztes-licht-des-tages-latergram
FB: https://facebook.com/10153891342010645

So something is different here... 
- why is the "See Original"-link here working?
- or is the "Original: [url]"-link the connection for bridgy?

**Comment by kylewm** [comment]
> or is the "Original: [url]"-link the connection for bridgy?

It's that one. Facebook doesn't rewrite links in the body of the post; it only tries to rewrite the links that are hidden in metadata (that's what See Original refers to ... [see here](http://indiewebcamp.com/POSSE_to_Facebook#See_Original) for more detail than you probably want ;)

We'd have to do something similar in the body of short posts to get backfeed to work reliably. It's unfortunate because imho it really does not look good, e.g. 

```
I'm at the supermarket

(Original: https://kylewm.com/2016/im-at-the-supermarket)
```

@snarfed, am I right in thinking there's a trick in Bridgy to associate app-scoped-ID with username, so that posse-post-discovery could conceivably work if Known published rel=syndication urls in the proper format? Right now rel-syndication is like

  https://facebook.com/12802152/posts/10101606868544479

would it make a difference if it was

  https://facebook.com/kyle.mahan/posts/10101606868544479

instead?

**Comment by snarfed** [comment]
bridgy does try to detect and handle usernames in syndication urls, yes: https://github.com/snarfed/bridgy/blob/master/facebook.py#L186 . facebook doesn't actually *tell* us users' usernames any more in API v2.0, but we infer them from syndication urls pretty aggressively - https://github.com/snarfed/bridgy/blob/master/facebook.py#L278 - so i think this should work.

**Comment by kylewm** [comment]
Cool, thanks!

> facebook doesn't actually tell us users' usernames

Heh, same problem from the publishing end. In silo.pub, I added a config screen where you can tell it your username... Maybe need to do the same thing here. I'll experiment a little.

**Comment by kylewm** [comment]
Hot damn, posse post discovery works if you include the username URL instead of the app-scoped ID URL.

i.e., this syndication URL worked: `https://www.facebook.com/junebug.parks.mahan/posts/143374809378388`

this one didn't: `https://facebook.com/143025379413331/posts/143326679383201`

(I stole your cat test user idea @snarfed)

So that's great news! We can get rid of "See Original" on notes, and just have to figure out a way to construct the right kind of syndication URLs on publishing.

**Comment by snarfed** [comment]
woo! good news indeed. we've spent too much of our lives catering to the Facebook API's cruel whims. glad to hear some of that work has stuck.

for known, you could (try to) extract the facebook username from the FB profile link that's displayed on the front page, right?
