### ISSUE TITLE
encoding/escape problem in body of bookmark 

### ISSUE THREAD

**Issue by matzoman** [idno/Facebook#35]
I entered this text for a bookmark:

`Ein guter (Erfahrungs-)Bericht zu einer Geburt. Auch für Männer eine Leseempfehlung!`

and this is on fb:

`Ein guter (Erfahrungs-)Bericht zu einer Geburt. Auch f&uuml;r M&auml;nner eine Leseempfehlung!`

(With a photo post and umlauts in the title I had no problem today.)

When I have more time I will investigate further. 

**edit**: Github parsed my text. now it's visible.

**Comment by kylewm** [comment]
Hmm, what is different between those two texts?

**Comment by matzoman** [comment]
I made an edit to show the problem...

**Comment by kylewm** [comment]
ahh, this should have been fixed in https://github.com/idno/Facebook/commit/223ca82183692082e0d266c15a6a6aecca447874

do you have the latest code from git?

**Comment by matzoman** [comment]
yes, i'm running old code. my bad. thanks for the heads up!
