### ISSUE TITLE
Location check-in Facebook

### ISSUE THREAD

**Issue by fraserYT** [idno/Facebook#37]
Will it ever be possible to add a location checkin to Facebook in the same way the Foursquare plugin allows with Foursquare, or is this another one of those arbitrary things that Facebook doesn't allow?

**Comment by kylewm** [comment]
This is tough to do without requiring you to explicitly select a venue from the Facebook database. (I tried it on my website and it would usually check me in to a weird place across the street from wherever I was)

@snarfed addressed this for himself by posting the check in to Facebook first and then backfilling the post to his site with snarfed/ownyourcheckins

**Comment by fraserYT** [comment]
That makes sense that it would be complicated now you explain it. I'll take a look at ownyourcheckins. Thanks
