### ISSUE TITLE
Access token / Session has expired - how can I fix that?

### ISSUE THREAD

**Issue by matzoman** [idno/Facebook#38]
Hi,

i found these log entry in my error log today:

[Wed Apr 06 12:56:58 2016] [warn] [client 84.141.126.8] mod_fcgid: stderr: Known (known.matthias.welling.io): info - Error validating access token: Session has expired on Saturday, 26-Mar-16 06:31:46 PDT. The current time is Wednesday, 06-Apr-16 03:56:59 PDT., referer: http://known.matthias.welling.io/photo/edit/691d1ce9f6d082b617829b3e66f9a1d7
[Wed Apr 06 12:56:58 2016] [warn] [client 84.141.126.8] mod_fcgid: stderr: PHP Notice:  Undefined variable: result in /var/www/virtual/matzoman/known.matthias.welling.io/IdnoPlugins/Facebook/Main.php on line 234, referer: http://known.matthias.welling.io/photo/edit/691d1ce9f6d082b617829b3e66f9a1d7
[Wed Apr 06 12:56:58 2016] [warn] [client 84.141.126.8] mod_fcgid: stderr: Nothing was posted to Facebook: NULL, referer: http://known.matthias.welling.io/photo/edit/691d1ce9f6d082b617829b3e66f9a1d7

Can I some how reset my session in known? 
Or do I have to do something in my app in Facebook?

I checked the App ID & App Secret. They are both still correct.

I could reset the client token on the FB side. Does that the trick?

(I could not find an open or closed issue on that topic. If there one, please send me there :) )

**Comment by rikmendes** [comment]
for what I remember when I got this once was reset of the tokens on FB side should fix the problem.

**Comment by kylewm** [comment]
Facebook access tokens expire every so often (6 months?). Ideally Known could/should prompt you to reauthorize when it gets this error, but for now, all you can do is go to /account/facebook and disconnect and reconnect.

**Comment by matzoman** [comment]
disconnect and reconnect was successful! thx.
