### ISSUE TITLE
Configurable default posting level

### ISSUE THREAD

**Issue by mapkyca** [idno/Facebook#4]
It would be awesome if you could specify the default posting level posse posts are sent as (globally first of all).

Of course I'm not sure if this is something that the facebook api supports...

**Comment by kylewm** [comment]
> default posting level 

Do you mean the privacy settings on Facebook? You can set this per-app within Facebook itself at https://www.facebook.com/settings?tab=applications

**Comment by mapkyca** [comment]
Per app setting, closing
