### ISSUE TITLE
API is completely out of sync

### ISSUE THREAD

**Issue by benwerd** [idno/Facebook#45]
Authenticating simply doesn't work anymore. This needs to be brought in line with the current Facebook API.

**Comment by mruncieman** [comment]
<a href="https://github.com/idno/Facebook/issues/45" class="u-in-reply-to"></a>My site stopped working with facebook about a week ago. Is anyone aware of any quick/easy changes that could be made to get it working again?

**Comment by rikmendes** [comment]
Still working here on 2 different knowns domains... Strange.. But expecting breakage soon.. On Mar 28, 2018 7:30 PM, Michael Runcieman <notifications@github.com> wrote:My site stopped working with facebook about a week ago. Is anyone aware of any quick/easy changes that could be made to get it working again?

**Comment by mapkyca** [comment]
<a href="https://github.com/idno/Facebook/issues/45" class="u-in-reply-to"></a>Mine works too.

Have y'all been tracking api changes in your app on facebook? IIRC there's some action you need to take on that end if you created your app ages ago...

**Comment by mruncieman** [comment]
<a href="https://github.com/idno/Facebook/issues/45" class="u-in-reply-to"></a>Are you able to disconnect your Known instance and reconnect? 

I click on the Connect to Facebook button, it redirects and successfully authenticates against Facebook, but when I redirect back to my site I still have a "Connect to Facebook" button (where as previously it would change to "Disconnect from Facebook").
