### ISSUE TITLE
Facebook Connect failing

### ISSUE THREAD

**Issue by skddc** [idno/Facebook#49]
![screenshot from 2018-08-11 10-44-09](https://user-images.githubusercontent.com/842/43989975-caca5638-9d54-11e8-93f2-f27a971d806a.png)

Please note: this is a different scope from what was fixed in May in #46, and which is also not included anymore in the current FB documentation.

**Comment by mapkyca** [comment]
Not a bug, sadly... Facebook changed their API to block third parties posting to their profile. Sucks, but there's nothing that can be done, sadly.

**Comment by raucao** [comment]
Oh wow, so there's no way whatsoever that anyone but Facebook can post to user profiles now? That would be incredibly sad.

**Comment by mapkyca** [comment]
Nope. Even WordPress have shut down their support for cross posting in Jetpack :/

**Comment by raucao** [comment]
Ouch! Thanks for the update.
